# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 583)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Things = QtWidgets.QPushButton(self.centralwidget)
        self.Things.setGeometry(QtCore.QRect(0, 0, 161, 81))
        self.Things.setObjectName("Things")
        self.Things.clicked.connect(self.clickedThings)

        self.Services = QtWidgets.QPushButton(self.centralwidget)
        self.Services.setGeometry(QtCore.QRect(160, 0, 161, 81))
        self.Services.setObjectName("Services")
        self.Services.clicked.connect(self.clickedServices)

        self.Relationship = QtWidgets.QPushButton(self.centralwidget)
        self.Relationship.setGeometry(QtCore.QRect(320, 0, 161, 81))
        self.Relationship.setObjectName("Relationship")
        self.Relationship.clicked.connect(self.clickedRelationship)

        self.Recipe = QtWidgets.QPushButton(self.centralwidget)
        self.Recipe.setGeometry(QtCore.QRect(480, 0, 161, 81))
        self.Recipe.setObjectName("Recipe")
        self.Recipe.clicked.connect(self.clickedRecipe)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 132, 181, 121))
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Things.setText(_translate("MainWindow", "Things"))
        self.Services.setText(_translate("MainWindow", "Services"))
        self.Relationship.setText(_translate("MainWindow", "Relationship"))
        self.Recipe.setText(_translate("MainWindow", "Recipe"))
        self.label.setText(_translate("MainWindow", "Homepage"))

    def clickedThings(self):
        self.label.setText("4 Raspberry PIs")
        self.update()

    def clickedServices(self):
        self.label.setText("Turning On/Off LEDs \n Making the buzzer make noise")
        self.update()

    def clickedRelationship(self):
        self.label.setText("Relationship tab page")
        self.update()

    def clickedRecipe(self):
        self.label.setText("Recipe tab page")
        self.update()

    def update(self):
        self.label.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
